# Site settings
title: My Old Blog
email: admin@eaxi.com
description: > # this means to ignore newlines until "baseurl:"
  粤ICP备18134409号-1
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eaxi.com" # the base hostname & protocol for your site
twitter_username: seaprince1
github_username:  zend

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
